### CONCRETE TYPES
include("structs/disease/disease_progression.jl")
include("structs/registries/infection_registry.jl")
include("structs/registries/immunity_registry.jl")
include("structs/parameters.jl")
include("structs/entities.jl")
include("structs/vaccinations.jl")
include("structs/simulation.jl") 
include("structs/registries/registry_iterators.jl")
include("structs/batch.jl")
