name: Unit Tests
on:
  push:
    branches: [main, development]
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  Tests:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: |
          if ($Env:RUNNER_OS -eq "Windows") {
            choco install pandoc -y
          } elseif ($Env:RUNNER_OS -eq "Linux") {
            sudo apt-get update -qq  
            sudo apt-get install -y pandoc
          } elseif ($Env:RUNNER_OS -eq "macOS") {
            brew install pandoc
          }
        shell: pwsh
      - name: Install TeX
        run: |
          if ($Env:RUNNER_OS -eq "Windows") {
            choco install miktex -y
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv
          } elseif ($Env:RUNNER_OS -eq "Linux") {
            sudo apt-get update -qq
            sudo apt-get install -y texlive texlive-xetex
          } elseif ($Env:RUNNER_OS -eq "macOS") {
            brew install --cask mactex
            Add-Content -Path $Env:GITHUB_PATH -Value "/Library/TeX/texbin"
          }
        shell: pwsh
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.3'                         
          show-versioninfo: false              
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.os == 'ubuntu-latest'
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # slug: IMMIDD/GEMS
          # file: lcov.info
          # fail_ci_if_error: true
