name: Unit Tests
on:
  push:
    branches: [main, development]
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  Tests:
    name: Run Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MiKTeX
        run: choco install miktex -y
      - name: Install Pandoc
        run: choco install pandoc -y
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.3'                         
          show-versioninfo: false              
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # slug: IMMIDD/GEMS
          # file: lcov.info
          # fail_ci_if_error: true
